# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SwiftBaseProject' do

pod 'Alamofire', '~> 3.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'R.swift'
pod 'HanekeSwift'

end

target 'SwiftBaseProjectTests' do

end

target 'SwiftBaseProjectUITests' do

end

